### ISSUE TITLE
Error using apprise when a container updates

### ISSUE THREAD

**Issue by eddiebeazer** [shizunge/gantry#14]
I run this as a cron job and when there is a container that is updated I'm getting an error of "Invalid JSON specified.".  Is there anyway to use a debug mode so I can see the json and see if its a user or or something that needs to be updated.

The other issue I had is most likely a separate issue but the space separated list do not work for the filter.  Only the first service is picked.  Not sure if I entered it wrong but I also saw this in the code base

```
local SERVICES_FILTERS="${GANTRY_SERVICES_FILTERS:-""}"
```

Shouldn't the above be this

```
local SERVICES_FILTERS="${GANTRY_SERVICES_FILTERS:-" "}"
```

Also thanks for this, the only swarm updater that works for me

**Comment by shizunge** [comment]
Sorry I did not personally use apprise, so I migrate it from shepherd. 

The source code is at [notification.sh](https://github.com/shizunge/gantry/blob/main/src/notification.sh). It is a `curl` command. 

If you can help debug this that would be great.

I will take a look at the second problem later.

**Comment by eddiebeazer** [comment]
Thanks for the reply. I set the logging to debug and I'll see if it prints out the json I need to debug the curl request. 

As for the issue with the delimiter, I just used the labels feature with just one label and applied them to the services I wanted to be updated. 

If you're strapped for time, I would just update the docs instead and remove the other filters. The label mechanism is similar to watchtowerrr

**Comment by eddiebeazer** [comment]
I just reviewed my logs with it set to debug and it did not print the JSON.  What log level would I need to see the failing JSON so I can debug it?

**Comment by trajano** [comment]
Is `notify_via_apprise` even called from anywhere?

**Comment by trajano** [comment]
I eventually found it, I created a #15  to clarify the documentation

**Comment by shizunge** [comment]
Is there a problem with apprise anymore? If no, we can close this bug.

For the filter, if you still have problem, please open a new bug. Let us track a single issue within a bug.
I guess you hit this: https://github.com/shizunge/gantry/blob/main/docs/faq.md#how-to-filters-multiple-services-by-name

**Comment by shizunge** [comment]
Document updated via #15.

Closed as not heard feedback from reporter on additional issues.

**Comment by shizunge** [comment]
The latest release fixed an error in Apprise Notification.

[Tests](https://github.com/shizunge/gantry/blob/main/tests/gantry_notify_spec.sh) are added to catch future failures.
