### ISSUE TITLE
DockerHub limit consumption

### ISSUE THREAD

**Issue by AkElie** [shizunge/gantry#16]
All the images used in the cluster are pulled from local docker registry on the network, however each time gantry is launched, docker Hub limit is decreased by 1.

Im using this env to point to the local reg:
GANTRY_REGISTRY_HOST=

Can you help me stop the docker Hub limit from being consumed.

**Comment by shizunge** [comment]
Can you send me the log?

**Comment by shizunge** [comment]
And how do you start the service?

**Comment by shizunge** [comment]
Please try `docker pull ghcr.io/shizunge/gantry:dev-1698894765`

**Comment by AkElie** [comment]
docker pull ghcr.io/shizunge/gantry:dev-1698894765, Thanks for your reply, this image actually works. I start the service in a docker compose file

**Comment by shizunge** [comment]
create a new release
